import type { IndustryItem } from "./types";

export const industriesHeaderContent = {
  label: "SECTOR EXPERTISE",
  title: "Industry Expertise That Drives Business Growth.",
  description:
    "Symbio Advisory partners with organizations across diverse industries, delivering advisory, audit, tax, compliance, ERP implementation, legal support, and business transformation solutions tailored to sector-specific challenges.",
  stats: [
    { value: "15+", label: "Industries Served" },
    { value: "100+", label: "Business Engagements" },
    { value: "20+", label: "Years Combined Experience" },
  ],
  ctaLabel: "Explore Our Services →",
  ctaHref: "/services",
} as const;

export const industriesData: IndustryItem[] = [
  {
    id: "retail-distribution",
    title: "Retail & Distribution",
    slug: "retail-distribution",
    image:
      "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Modern retail distribution facility and automated logistics warehouse",
    executiveSummary:
      "Modernizing retail and distribution networks through automated inventory control, multi-channel tax structuring, ERP integration, and supply chain audit advisory.",
    challenges: [
      "Multi-channel Inventory Tracking",
      "Sales Tax & VAT Compliance",
      "Supply Chain Margin Leakage",
      "Point-of-Sale System Integration",
      "Working Capital Optimization",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "25+ Enterprises",
      typicalCompanySize: "$5M – $100M ARR",
      coreServices: "ERP, Tax Advisory & Audit",
    },
    ctaLink: "/services",
  },
  {
    id: "manufacturing-extraction",
    title: "Manufacturing & Extraction",
    slug: "manufacturing-extraction",
    image:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Advanced industrial manufacturing plant and precision production facility",
    executiveSummary:
      "Supporting manufacturing and extraction businesses through ERP implementation, internal controls, audit, tax advisory, compliance, financial reporting, and operational transformation.",
    challenges: [
      "Regulatory & Environmental Compliance",
      "Cost Accounting & Margin Optimization",
      "Complex ERP & Shop-Floor Integration",
      "Plant Maintenance Internal Controls",
      "Capital Expenditure & Cash Flow",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "30+ Plants & Facilities",
      typicalCompanySize: "$10M – $250M ARR",
      coreServices: "Costing, Audit & ERP",
    },
    ctaLink: "/services",
  },
  {
    id: "engineering-construction",
    title: "Engineering & Construction",
    slug: "engineering-construction",
    image:
      "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Commercial infrastructure bridge and modern engineering project",
    executiveSummary:
      "Empowering engineering contractors and infrastructure developers with percentage-of-completion accounting, joint venture tax structuring, project audit, and risk management.",
    challenges: [
      "Project Accounting & Cost Overruns",
      "Joint Venture & Subcontractor Tax",
      "Contractual Risk & Dispute Support",
      "Capital Equipment Depreciation",
      "Regulatory License Compliance",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "20+ Contractors",
      typicalCompanySize: "$15M – $500M Portfolio",
      coreServices: "Project Accounting & Legal",
    },
    ctaLink: "/services",
  },
  {
    id: "healthcare-pharmaceuticals",
    title: "Healthcare & Pharmaceuticals",
    slug: "healthcare-pharmaceuticals",
    image:
      "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Modern hospital research wing and pharmaceutical laboratory",
    executiveSummary:
      "Navigating complex healthcare regulations, DRAP compliance, clinical audit, pharmaceutical tax structuring, and hospital financial management systems.",
    challenges: [
      "Strict Regulatory & Drug Licensing",
      "R&D Tax Credits & Subsidies",
      "Hospital Revenue Cycle Management",
      "Medical Supply Chain Audit",
      "Patient Data Governance",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "18+ Health Networks",
      typicalCompanySize: "$8M – $150M ARR",
      coreServices: "DRAP Advisory & Compliance",
    },
    ctaLink: "/services",
  },
  {
    id: "education",
    title: "Education",
    slug: "education",
    image:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Modern university campus and professional innovation center",
    executiveSummary:
      "Assisting private universities, school networks, and edtech platforms with non-profit tax exemptions, endowment fund audits, regulatory accreditation, and ERP systems.",
    challenges: [
      "Tax Exemption & Trust Structuring",
      "Endowment Fund Governance",
      "Student Fee Billing & Automation",
      "Regulatory Accreditation Audit",
      "Faculty Payroll & Compliance",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "15+ Institutions",
      typicalCompanySize: "1,000 – 25,000 Students",
      coreServices: "Governance & Tax Exemption",
    },
    ctaLink: "/services",
  },
  {
    id: "it-telecommunications",
    title: "IT & Telecommunications",
    slug: "it-telecommunications",
    image:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "High-density enterprise data center and cloud infrastructure hub",
    executiveSummary:
      "Accelerating technology firms and telecom operators with software revenue recognition, export tax concessions, IP protection, AI integration, and global transfer pricing.",
    challenges: [
      "Cross-Border Software Revenue Tax",
      "Export Exemption Compliance",
      "Intellectual Property Valuation",
      "Infrastructure CapEx Financing",
      "Data Sovereignty & Cybersecurity",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "35+ Tech Companies",
      typicalCompanySize: "$2M – $80M ARR",
      coreServices: "Export Tax & Transfer Pricing",
    },
    ctaLink: "/services",
  },
  {
    id: "housing-real-estate",
    title: "Housing & Real Estate",
    slug: "housing-real-estate",
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Commercial financial district skyline and modern office towers",
    executiveSummary:
      "Advising commercial developers, REITs, and housing societies on property tax structuring, escrow account audits, regulatory approvals, and land holding compliance.",
    challenges: [
      "Property Tax & Stamp Duty Compliance",
      "RERA & Municipal Regulatory Approvals",
      "Escrow Account Financial Audits",
      "Land Acquisition Legal Due Diligence",
      "Capital Gains Tax Optimization",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "22+ Real Estate Groups",
      typicalCompanySize: "$20M – $400M Assets",
      coreServices: "Tax Advisory & Legal Support",
    },
    ctaLink: "/services",
  },
  {
    id: "hospitality",
    title: "Hospitality",
    slug: "hospitality",
    image:
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Luxury hotel interior and executive hospitality lounge",
    executiveSummary:
      "Optimizing hotel groups, resort chains, and service businesses through room yield analytics, luxury tax compliance, POS integration, and operational audits.",
    challenges: [
      "Seasonal Cash Flow Management",
      "Sales Tax & Service Tax Audits",
      "Franchise Royalty Tax Structuring",
      "Food & Beverage Cost Accounting",
      "Staff Payroll & Service Charges",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "14+ Hotel Groups",
      typicalCompanySize: "$4M – $60M ARR",
      coreServices: "Tax Compliance & POS Audit",
    },
    ctaLink: "/services",
  },
  {
    id: "foods-beverages",
    title: "Foods & Beverages",
    slug: "foods-beverages",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Food processing line and beverage manufacturing facility",
    executiveSummary:
      "Guiding food processors, beverage brands, and FMCG manufacturers through food safety compliance, recipe costing, yield loss audits, and ERP automation.",
    challenges: [
      "Food Authority Safety Regulations",
      "Perishable Goods Inventory Losses",
      "FMCG Sales Tax Withholding",
      "Recipe & Batch Costing Accuracy",
      "Cold-Chain Logistics Audit",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "20+ FMCG Brands",
      typicalCompanySize: "$6M – $120M ARR",
      coreServices: "Batch Costing & Compliance",
    },
    ctaLink: "/services",
  },
  {
    id: "beauty-salon",
    title: "Beauty & Salon",
    slug: "beauty-salon",
    image:
      "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Modern luxury salon lounge and aesthetic wellness facility",
    executiveSummary:
      "Providing salon chains and cosmetic brands with retail chain tax compliance, commission structure audits, inventory management, and multi-location ERPs.",
    challenges: [
      "Multi-Branch Tax Consolidation",
      "Commission & Royalty Audits",
      "Cosmetics Import Duty Tax",
      "POS & Inventory Leakage",
      "Franchise Financial Controls",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "12+ Salon Chains",
      typicalCompanySize: "$1M – $15M ARR",
      coreServices: "Multi-Branch Tax & POS",
    },
    ctaLink: "/services",
  },
  {
    id: "oil-banaspati",
    title: "Oil & Banaspati",
    slug: "oil-banaspati",
    image:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Industrial edible oil refinery and energy processing plant",
    executiveSummary:
      "Delivering high-stakes financial advisory, import duty tax structuring, raw material hedging audits, and ERP systems for edible oil and ghee refiners.",
    challenges: [
      "Volatile Commodity Duty Taxes",
      "Import L/C Financial Advisory",
      "Refining Yield & Loss Audits",
      "Price Control Regulatory Reports",
      "Working Capital Credit Lines",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "10+ Refineries",
      typicalCompanySize: "$25M – $300M ARR",
      coreServices: "Duty Tax & Import Advisory",
    },
    ctaLink: "/services",
  },
  {
    id: "textile-leather",
    title: "Textile & Leather",
    slug: "textile-leather",
    image:
      "https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "High-end industrial textile manufacturing mill and weaving floor",
    executiveSummary:
      "Strengthening export textile mills and leather tanneries with sales tax refund processing, custom duty drawbacks, labor compliance, and global trade audit.",
    challenges: [
      "Sales Tax Refund Delays",
      "Customs Duty Drawback Audits",
      "Social & Environmental Compliance",
      "Export Financing & LC Accounting",
      "Waste & Scrap Revenue Audits",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "28+ Export Mills",
      typicalCompanySize: "$12M – $200M ARR",
      coreServices: "Tax Refunds & Export Audit",
    },
    ctaLink: "/services",
  },
  {
    id: "non-profit-organizations",
    title: "Non-Profit Organizations",
    slug: "non-profit-organizations",
    image:
      "https://images.unsplash.com/photo-1532629345422-7515f3d16bb0?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Global development team and non-profit community initiative",
    executiveSummary:
      "Navigating NPO tax exemption approvals under section 2(36), donor fund audits, EAD clearance, FCRA compliance, and governance for international and local NGOs.",
    challenges: [
      "Section 2(36) Tax Exemption Approval",
      "Foreign Contribution & EAD Clearance",
      "Donor Specific Grant Audits",
      "Board Governance & Regulatory Reporting",
      "Withholding Tax Exemption Certificates",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "25+ NGOs & Foundations",
      typicalCompanySize: "$500K – $50M Grants",
      coreServices: "NPO Tax Exemption & Grant Audit",
    },
    ctaLink: "/services",
  },
  {
    id: "poultry-feed",
    title: "Poultry & Feed",
    slug: "poultry-feed",
    image:
      "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Modern agri-business feed mill and automated poultry farm facility",
    executiveSummary:
      "Providing poultry integrators, hatcheries, and feed mills with agricultural tax concessions, mortality loss accounting, ERP integration, and farm audit.",
    challenges: [
      "Agricultural Tax Exemption Limits",
      "Feed Raw Material Inventory Losses",
      "Biological Asset Valuation",
      "Hatchery & Farm ERP Integration",
      "Poultry Sales Tax Withholding",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "16+ Feed Mills & Farms",
      typicalCompanySize: "$5M – $80M ARR",
      coreServices: "Farm ERP & Agri-Tax",
    },
    ctaLink: "/services",
  },
  {
    id: "co-operative-societies",
    title: "Co-operative Societies",
    slug: "co-operative-societies",
    image:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    imageAlt: "Executive co-operative board meeting and governance assembly",
    executiveSummary:
      "Supporting co-operative housing and credit societies with statutory audits, registrar annual filings, member share accounting, and dispute resolution.",
    challenges: [
      "Statutory Co-operative Audits",
      "Registrar Annual Return Filings",
      "Member Share Capital Governance",
      "Taxation on Surplus & Dividends",
      "By-Laws & Legal Dispute Advisory",
    ],
    howSymbioHelps: [
      "Audit",
      "Tax Advisory",
      "ERP Implementation",
      "Compliance",
      "Business Advisory",
      "Financial Reporting",
      "Corporate Governance",
      "Automation",
    ],
    snapshot: {
      businessesServed: "18+ Co-operative Bodies",
      typicalCompanySize: "500 – 10,000 Members",
      coreServices: "Statutory Audit & Registrar Compliance",
    },
    ctaLink: "/services",
  },
];
